export const REQUEST_ACCOUNTS         = 'keppel/REQUEST_ACCOUNTS';
export const RECEIVE_ACCOUNTS         = 'keppel/RECEIVE_ACCOUNTS';
export const REQUEST_ACCOUNTS_FAILURE = 'keppel/REQUEST_ACCOUNTS_FAILURE';

export const UPDATE_ACCOUNT           = 'keppel/UPDATE_ACCOUNT';

export const REQUEST_REPOSITORIES          = 'keppel/REQUEST_REPOSITORIES';
export const RECEIVE_REPOSITORIES          = 'keppel/RECEIVE_REPOSITORIES';
export const REQUEST_REPOSITORIES_FINISHED = 'keppel/REQUEST_REPOSITORIES_FINISHED';
export const REQUEST_REPOSITORIES_FAILURE  = 'keppel/REQUEST_REPOSITORIES_FAILURE';
