((app) ->
  app.REQUEST_CLUSTERS          = 'REQUEST_CLUSTERS'
  app.REQUEST_CLUSTERS_FAILURE  = 'REQUEST_CLUSTERS_FAILURE'
  app.RECEIVE_CLUSTERS          = 'RECEIVE_CLUSTERS'
  app.DELETE_CLUSTER            = 'DELETE_CLUSTER'
  app.DELETE_CLUSTER_FAILURE    = 'DELETE_CLUSTER_FAILURE'

)(kubernetes)
