((app) ->
  app.REQUEST_CLUSTERS          = 'REQUEST_CLUSTERS'
  app.REQUEST_CLUSTERS_FAILURE  = 'REQUEST_CLUSTERS_FAILURE'
  app.RECEIVE_CLUSTERS          = 'RECEIVE_CLUSTERS'
  app.DELETE_CLUSTER            = 'DELETE_CLUSTER'
  app.DELETE_CLUSTER_FAILURE    = 'DELETE_CLUSTER_FAILURE'

  # -------- FORMS --------------
  app.PREPARE_CLUSTER_FORM      = 'PREPARE_CLUSTER_FORM'
  app.RESET_CLUSTER_FORM        = 'RESET_CLUSTER_FORM'
  app.UPDATE_CLUSTER_FORM       = 'UPDATE_CLUSTER_FORM'
  app.SUBMIT_CLUSTER_FORM       = 'SUBMIT_CLUSTER_FORM'
  app.CLUSTER_FORM_FAILURE      = 'CLUSTER_FORM_FAILURE'

)(kubernetes)
