# Pull base image.
FROM ruby:2.4.1-slim-stretch

RUN apt update
RUN apt -y install \
  git \
  curl \
  fontconfig \
  build-essential \
  patch \
  ruby-dev \
  zlib1g-dev \
  liblzma-dev \
  && rm -rf /var/cache/apt/*

# Install phantomjs
RUN cd /usr/local/share \
  && curl -L http://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar xj \
  && ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/share/phantomjs \
  && ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin/phantomjs \
  && ln -s /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs \
  && phantomjs --version

RUN mkdir -p /app

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install --without default test development production doc --standalone integration_test

RUN rm -rf /app/Gemfile*
