((app) ->
  ########## EVENTS #########
  app.REQUEST_EVENTS                  = 'REQUEST_EVENTS'
  app.RECEIVE_EVENTS                  = 'RECEIVE_EVENTS'
  app.REQUEST_EVENTS_FAILURE          = 'REQUEST_EVENTS_FAILURE'
  app.UPDATE_FILTER                   = 'UPDATE_FILTER'
  app.UPDATE_OFFSET                   = 'UPDATE_OFFSET'
  app.TOGGLE_EVENT_DETAILS_VISIBLE    = 'TOGGLE_EVENT_DETAILS_VISIBLE'
  app.REQUEST_EVENT_DETAILS           = 'REQUEST_EVENT_DETAILS'
  app.REQUEST_EVENT_DETAILS_FAILURE   = 'REQUEST_EVENT_DETAILS_FAILURE'
  app.RECEIVE_EVENT_DETAILS           = 'RECEIVE_EVENT_DETAILS'



)(audit)
