//Takes a Castellum resource configuration and checks if it conforms to the
//format generated by this UI. Possible return values:
//
//  { custom: false, value: null }  -> autoscaling not enabled
//  { custom: false, value: <int> } -> autoscaling enabled through this UI
//  { custom: true }                -> autoscaling enabled through other Castellum client
export const parseConfig = (config) => {
  if (!config) {
    return { custom: false, value: null };
  }
  if (!config.size_steps.single) {
    return { custom: true };
  }
  if (!config.low_threshold || !config.critical_threshold || config.high_threshold) {
    return { custom: true };
  }
  const { usage_percent: lowPerc, delay_seconds: lowSecs } = config.low_threshold;
  const { usage_percent: criticalPerc }                    = config.critical_threshold;
  if (lowSecs != 60) {
    return { custom: true };
  }
  if (lowPerc != criticalPerc - 0.1) {
    return { custom: true };
  }
  return { custom: false, value: 100 - criticalPerc };
};

//Generate a Castellum resource configuration that parseConfig() recognizes.
export const generateConfig = (value) => ({
  low_threshold:      { usage_percent: 99.9 - value, delay_seconds: 60 },
  critical_threshold: { usage_percent: 100. - value },
  size_steps:         { single: true },
});

const renderConfigUI = ({ projectID, config, editValue, handleEditValue }) => {
  const parsed = parseConfig(config);
  if (parsed.custom) {
    return <em>Custom configuration (applied via API)</em>;
  }
  if (editValue === null) {
    if (parsed.value === null) {
      return <div className='text-muted'>Autoscaling not enabled</div>;
    } else {
      return <span>Ensure <strong>{parsed.value}%</strong> free quota</span>;
    }
  } else {
    return <span>
      Ensure{' '}
      <input type='number'
        className='form-control' style={{width:'auto',display:'inline'}}
        min='0' max='90'
        value={editValue}
        onChange={(e) => handleEditValue(projectID, e.target.value)}
      />
      {' '}% free quota (leave empty to disable)
    </span>;
  }
};

export const AutoscalingConfigItem = ({ project, config, assetType, ...editorProps }) => (
  <tr>
    <td className='col-md-4'>
      {project.name}
      <div className='small text-muted'>{project.id}</div>
    </td>
    <td className='col-md-8'>
      { config.isFetching ? (
        <div><span className='spinner'/> Loading...</div>
      ) : config.data == null ? (
        <div className='alert alert-error'>Could not load autoscaling configuration for project</div>
      ) : (
        renderConfigUI({
          projectID: project.id,
          config: config.data[assetType],
          ...editorProps,
        })
      )}
    </td>
    <td></td>
  </tr>
);


