module ManualValidation
  extend ActiveSupport::Concern

  def self.included(base)
    base.send :validate, :validate_early_errors
  end

  # Add a validation error generated by the controller. Since errors.add()
  # only works during validate(), we need to save these errors if we want to
  # present these errors in a simple_form.
  def add_validation_error(field, error)
    (@early_errors ||= []).push([field, error])
  end

  protected

  def validate_early_errors
    (@early_errors || []).each { |field, error| errors.add(field, error) }
  end
end
