FROM ruby:2.5-alpine3.10

LABEL source_repository="https://github.com/sapcc/elektra"

RUN apk --no-cache add git curl

RUN apk update && apk add --no-cache fontconfig && \
  mkdir -p /usr/share && \
  cd /usr/share \
  && curl -L https://github.com/Overbryd/docker-phantomjs-alpine/releases/download/2.11/phantomjs-alpine-x86_64.tar.bz2 | tar xj \
  && ln -s /usr/share/phantomjs/phantomjs /usr/bin/phantomjs \
  && phantomjs --version

# Install gems with native extensions before running bundle install
# This avoids recompiling them everytime the Gemfile.lock changes.
# The versions need to be kept in sync with the Gemfile.lock
RUN  apk add build-base --virtual .builddeps  \
  && gem install nokogiri -v 1.12.5 \
  && gem install websocket-driver -v 0.7.2 \
  && gem sources -c \
  && rm -f /usr/local/bundle/cache/*

RUN mkdir -p /app

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install --without default test development production doc --standalone integration_test api_client


