FROM keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/library/node:12-buster

WORKDIR /home/app/webapp
ADD package.json yarn.lock ./
RUN yarn

# docker build -t elektra-jest-tests -f docker/Dockerfile.jest-tests
# docker run -it --rm  -v /workspace/elektra:/app -w /app elektra-jest-tests yarn test