// -------- CLUSTERS --------------
export const REQUEST_CLUSTERS = "REQUEST_CLUSTERS"
export const REQUEST_CLUSTERS_FAILURE = "REQUEST_CLUSTERS_FAILURE"
export const RECEIVE_CLUSTERS = "RECEIVE_CLUSTERS"

export const REQUEST_CLUSTER = "REQUEST_CLUSTER"
export const REQUEST_CLUSTER_FAILURE = "REQUEST_CLUSTER_FAILURE"
export const RECEIVE_CLUSTER = "RECEIVE_CLUSTER"
export const START_POLLING_CLUSTER = "START_POLLING_CLUSTER"
export const STOP_POLLING_CLUSTER = "STOP_POLLING_CLUSTER"

export const DELETE_CLUSTER = "DELETE_CLUSTER"
export const DELETE_CLUSTER_FAILURE = "DELETE_CLUSTER_FAILURE"

export const REQUEST_CLUSTER_EVENTS = "REQUEST_CLUSTER_EVENTS"
export const REQUEST_CLUSTER_EVENTS_FAILURE = "REQUEST_CLUSTER_EVENTS_FAILURE"
export const RECEIVE_CLUSTER_EVENTS = "RECEIVE_CLUSTER_EVENTS"

export const REQUEST_CREDENTIALS = "REQUEST_CREDENTIALS"
export const REQUEST_CREDENTIALS_FAILURE = "REQUEST_CREDENTIALS_FAILURE"
export const RECEIVE_CREDENTIALS = "RECEIVE_CREDENTIALS"

export const REQUEST_SETUP_INFO = "REQUEST_SETUP_INFO"
export const REQUEST_SETUP_INFO_FAILURE = "REQUEST_SETUP_INFO_FAILURE"
export const RECEIVE_SETUP_INFO = "RECEIVE_SETUP_INFO"
export const SETUP_INFO_DATA = "SETUP_INFO_DATA"

// -------- FORMS --------------
export const PREPARE_CLUSTER_FORM = "PREPARE_CLUSTER_FORM"
export const RESET_CLUSTER_FORM = "RESET_CLUSTER_FORM"
export const UPDATE_CLUSTER_FORM = "UPDATE_CLUSTER_FORM"
export const UPDATE_NODE_POOL_FORM = "UPDATE_NODE_POOL_FORM"
export const ADD_NODE_POOL = "ADD_NODE_POOL"
export const DELETE_NODE_POOL = "DELETE_NODE_POOL"
export const SUBMIT_CLUSTER_FORM = "SUBMIT_CLUSTER_FORM"
export const CLUSTER_FORM_FAILURE = "CLUSTER_FORM_FAILURE"
export const FORM_TOGGLE_ADVANCED_OPTIONS = "FORM_TOGGLE_ADVANCED_OPTIONS"
export const FORM_UPDATE_ADVANCED_VALUE = "FORM_UPDATE_ADVANCED_VALUE"
export const FORM_CHANGE_VERSION = "FORM_CHANGE_VERSION"
export const FORM_UPDATE_SSH_KEY = "FORM_UPDATE_SSH_KEY"
export const FORM_UPDATE_KEY_PAIR = "FORM_UPDATE_KEY_PAIR"
export const SET_CLUSTER_FORM_DEFAULTS = "SET_CLUSTER_FORM_DEFAULTS"
export const SET_CLUSTER_FORM_DEFAULT_VERSION =
  "SET_CLUSTER_FORM_DEFAULT_VERSION"

// -------- METADATA --------------
export const REQUEST_META_DATA = "REQUEST_META_DATA"
export const REQUEST_META_DATA_FAILURE = "REQUEST_META_DATA_FAILURE"
export const RECEIVE_META_DATA = "RECEIVE_META_DATA"

// -------- KUBERNIKUS INFO --------------
export const REQUEST_INFO = "REQUEST_INFO"
export const REQUEST_INFO_FAILURE = "REQUEST_INFO_FAILURE"
export const RECEIVE_INFO = "RECEIVE_INFO"
