# https://github.com/cypress-io/cypress-docker-images/tree/master/included
FROM keppel.eu-de-1.cloud.sap/ccloud-dockerhub-mirror/cypress/included:9.1.1
# install sorry cypress wrapper
# https://docs.sorry-cypress.dev/guide/get-started#install-cy2-and-cypress
RUN npm install -g cy2 && cy2 info
