#!/usr/bin/env ruby

require 'pathname'
ENV['BUNDLE_GEMFILE'] ||= File.expand_path("../Gemfile",
  Pathname.new(__FILE__).realpath)
require 'bundler/setup'

$:.unshift File.join(File.expand_path "../lib", __FILE__)

require 'chef/project_manifest' 
require 'chef/version'
project = Chef::ProjectManifest.new('chef', 'stable')
previous_stdout, $stdout = $stdout, $stderr
manifest = begin
	project.generate.keep_if {|k,v|%w{windows el ubuntu}.include?(k) }
ensure
	$stdout = previous_stdout
end

#discard versions for some platform versions
manifest['el'].keep_if {|k,v| %w{6 7}.include? k}
manifest['ubuntu'].keep_if {|k,v| %w{14.04 16.04}.include? k}

manifest.each do |platform, versions|
	versions.each do |version, archs|
		archs.each do |arch, chef_versions|
		manifest[platform][version][arch] = chef_versions.keys
		end
	end
end
puts JSON.pretty_generate(manifest)
