# frozen_string_literal: true

module Reports
  class CostController < DashboardController
    def index
      data =  '[[{ "region": "TAZ01", "year": 2018, "month": 5, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.25, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 5, "project_id": "project1", "object_id": "instance1","service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 1.25, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2018, "month": 4, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.90, "price_sec": 0.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 4, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 3.90, "price_sec": 0.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2018, "month": 3, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.45, "price_sec": 0.65, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 3, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 2.45, "price_sec": 1.65, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2018, "month": 2, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.33, "price_sec": 0.55, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 2, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 5.33, "price_sec": 3.55, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2018, "month": 1, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.88, "price_sec": 0.45, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 1, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 4.88, "price_sec": 1.45, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2017, "month": 12, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.62, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 12, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 2.62, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2017, "month": 11, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.22, "price_sec": 0.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 11, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 5.22, "price_sec": 2.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2017, "month": 10, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.15, "price_sec": 0.15, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 10, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 6.15, "price_sec": 1.15, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2017, "month": 9, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.99, "price_sec": 0.45, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 9, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 4.99, "price_sec": 0, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2017, "month": 8, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 1.25, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 8, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 1.25, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2017, "month": 7, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.5, "price_sec": 0.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 7, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 3.5, "price_sec": 2.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}],'\
              '[{ "region": "TAZ01", "year": 2017, "month": 6, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 2.25, "price_sec": 0.15, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 6, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 6.25, "price_sec": 3.15, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}]]'

      respond_to do |format|
        format.html
        format.json { render json: data }
      end
    end
  end
end
