# frozen_string_literal: true

module Reports
  class CostController < DashboardController
    def index
      # '{ "region": "TAZ01", "year": 2017, "month": 6, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 2.25, "price_sec": 0.15, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 6, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 6.25, "price_sec": 3.15, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2017, "month": 7, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.5, "price_sec": 0.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 7, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 3.5, "price_sec": 2.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2017, "month": 8, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 1.25, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 8, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 1.25, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2017, "month": 9, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.99, "price_sec": 0.45, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 9, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 4.99, "price_sec": 0, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2017, "month": 10, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.15, "price_sec": 0.15, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 10, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 6.15, "price_sec": 1.15, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2017, "month": 11, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.22, "price_sec": 0.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 11, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 5.22, "price_sec": 2.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2017, "month": 12, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.62, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2017, "month": 12, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 2.62, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2018, "month": 1, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.88, "price_sec": 0.45, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 1, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 4.88, "price_sec": 1.45, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2018, "month": 2, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.33, "price_sec": 0.55, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 2, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 5.33, "price_sec": 3.55, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\

      # data = '['\
      # '{ "region": "TAZ01", "year": 2018, "month": 3, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.45, "price_sec": 0.65, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 3, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 2.45, "price_sec": 1.65, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2018, "month": 4, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.90, "price_sec": 0.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 4, "project_id": "project1", "object_id": "instance1", "service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 3.90, "price_sec": 0.25, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},'\
      # '{ "region": "TAZ01", "year": 2018, "month": 5, "project_id": "project1", "object_id": "instance1", "service": "compute", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 0.25, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false},{ "region": "TAZ01", "year": 2018, "month": 5, "project_id": "project1", "object_id": "instance1","service": "swift", "measure": "ram", "allocation_type": "quota", "amount": 0.73,"amount_unit": "GiBh", "duration": 0.7, "duration_unit": "h", "price_loc": 1.25, "price_sec": 0.35, "currency": "EUR", "cost_object": "testCO", "cost_object_type": "CC","co_inherited": false}'\
      # ']'

      data = '['\
        '{"region":"eu-de-1","year":2018,"month":5,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"compute","measure":"ram","allocation_type":"quota","amount":7429.99348,"amount_unit":"GiBh","duration":742.99348,"duration_unit":"h","price_loc":20.12878,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":5,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"instance","measure":"os_windows","allocation_type":"usage","amount":170.27098,"amount_unit":"pieceh","duration":170.27098,"duration_unit":"h","price_loc":5.92056,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":5,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"block_storage","measure":"os_windows","allocation_type":"usage","amount":170.27098,"amount_unit":"pieceh","duration":170.27098,"duration_unit":"h","price_loc":2.5,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":5,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"shared_file_storage","measure":"os_windows","allocation_type":"usage","amount":170.27098,"amount_unit":"pieceh","duration":170.27098,"duration_unit":"h","price_loc":3.567,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":5,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"router","measure":"os_windows","allocation_type":"usage","amount":170.27098,"amount_unit":"pieceh","duration":170.27098,"duration_unit":"h","price_loc":37.89,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":5,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"loadbalancer","measure":"os_windows","allocation_type":"usage","amount":170.27098,"amount_unit":"pieceh","duration":170.27098,"duration_unit":"h","price_loc":1.23,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":5,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"licenses","measure":"os_windows","allocation_type":"usage","amount":170.27098,"amount_unit":"pieceh","duration":170.27098,"duration_unit":"h","price_loc":0.123,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":6,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"compute","measure":"ram","allocation_type":"quota","amount":2699.99763,"amount_unit":"GiBh","duration":269.99763,"duration_unit":"h","price_loc":7.31463,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":6,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"instance","measure":"os_windows","allocation_type":"usage","amount":93.00059,"amount_unit":"pieceh","duration":93.00059,"duration_unit":"h","price_loc":3.23379,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":6,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"router","measure":"os_windows","allocation_type":"usage","amount":93.00059,"amount_unit":"pieceh","duration":93.00059,"duration_unit":"h","price_loc":1.5,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false},'\
        '{"region":"eu-de-1","year":2018,"month":6,"project_id":"1d1ad583e98c4913a0226feac0f010f9","service":"block_storage","measure":"os_windows","allocation_type":"usage","amount":93.00059,"amount_unit":"pieceh","duration":93.00059,"duration_unit":"h","price_loc":3.9,"price_sec":0,"currency":"EUR","cost_object":"101050123","cost_object_type":"CC","co_inherited":false}'\
      ']'



      # data = services.masterdata_cockpit.get_project_costing

      respond_to do |format|
        format.html
        format.json { render json: data }
      end
    end
  end
end
